server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, routes, health, info


