eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  jpa:
    hibernate:
      ddl-auto: update
    showSql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/mss-user
    driverClassName: org.postgresql.Driver
    username: username
    password: password
